suborbital/subo

- go.mod
- go.sum
- vendor/github.com/suborbital/reactr/directive/directive.go
- vendor/modules.txt
This includes the latest version of Reactr which allows Subo to read schedules.
WAIT as Reactr needs to be tagged and used here before merging
> Update Reactr to include Schedules

- subo/command/build.go
- subo/context/buildcontext.go
Resolves https://github.com/suborbital/subo/issues/31
> Return error if `subo build` is run inside a Runnables directory

- subo/command/build.go
- subo/command/clean.go
- subo/command/create_project.go
- subo/command/create_release.go
- subo/command/create_runnable.go
- subo/util/config.go
- subo/util/log.go
- subo/util/templates.go
This refactors the template system to decouple updating templates from the create {runnable | project} commands.
Resolves https://github.com/suborbital/subo/issues/55
> Refactor templates system

- templates/project/Dockerfile.tmpl
> Use exec form instead of shell form for ENTRYPOINT in Dockerfile.tmpl

- README.md
> Update builders folder path in README

- builder/context/buildcontext.go
- subo/util/log.go
> When unable to readDir in context, log error and continue

- subo/command/create_project.go
- subo/command/create_runnable.go
- subo/main.go
- subo/root.go
This PR implements a simpler version of the changes suggested in #86 (thanks @samderlust!) and fixes a few typos.
Resolves #80
> subo CLI fixes and improvements

- .github/workflows/sanity.yml
- subo/command/compute_deploy_core.go
- subo/command/create_runnable.go
- subo/release/version.go
- templates/scc-k8s/scc-atmo-deployment.yaml.tmpl
- templates/scc-k8s/scc-controlplane-deployment.yaml.tmpl
This adds two nice-to-haves to the deploy command:
- Auto-detection of K8s storage class
- Auto-creation of configMap for control-plane configuration
> Improvements to `compute deploy core` command

- subo/command/compute_create_token.go
- subo/command/compute_deploy_core.go
- subo/util/token.go
fix https://github.com/suborbital/subo/issues/109
cc @jagger27 @cohix
> feat: get token from tmp file

- subo/command/compute_deploy_core.go
- subo/command/create_release.go
- subo/command/create_runnable.go
- subo/command/flags.go
- subo/localproxy/proxy.go
- subo/repl/repl.go
> Add configurable proxy port

- subo/command/build.go
> Fix subo build --docker segfaults

- main.go
> Check for empty message in updater

- builder/context/buildcontext.go
- builder/context/native.go
- builder/context/prereq.go
- subo/command/create_runnable.go
- templates/js/babel.config.js
- templates/js/jest.config.js
- templates/js/package.json.tmpl
- templates/js/src/env.d.ts
- templates/js/src/env.js
- templates/js/src/index.ts
- templates/js/src/lib.ts
- templates/js/tsconfig.json
- templates/js/webpack.config.js
Does what it says on the tin :)
> feat(builder): support for JS

- builder/builder.mk
- builder/docker/javascript/Dockerfile
> feat: Add builder-js docker image

- builder/context/native.go
> fix(builder): Only run Javy once for JS/TS Runnables

- builder/template/config.go
> Missing error assignment leads to missed error checking #185

- .github/workflows/ci.yml
- templates/tinygo/go.mod.tmpl
TinyGo has not yet been updated to 1.18.
> fix: Revert TinyGo go.mod.tmpl to 1.17

- builder/builder.go
- builder/builder.mk
- builder/docker/wat/Dockerfile
- builder/native.go
- builder/prereq.go
- project/context.go
- templates/wat/lib.wat
> feat: Add `wat` language builder

- builder/docker/assemblyscript/Dockerfile
- builder/docker/grain/Dockerfile
- builder/docker/javascript/Dockerfile
- builder/docker/rust/Dockerfile
- builder/docker/swift/Dockerfile
- builder/docker/tinygo/Dockerfile
- builder/docker/wat/Dockerfile
Removes uneeded WORKDIRs. Cleans up order of operations. Mixes some
layers intentionally.
> chore: simplify builder Dockerfiles

- .github/workflows/ci.yml
- builder/docker/javascript/Dockerfile
Adds Javascript and TypeScript to the matrix smoke test.
> chore(ci): add js smoketests

- .subo.yml
GitHub Actions takes care of the removed steps.
> chore(ci): Move release tasks to GHA

- builder/docker/javascript/Dockerfile
> fix(builder): Allow JS to bind to resp_set_header

- builder/docker/tinygo/Dockerfile
I like this new workflow a lot!
> chore: Update suborbital/tinygo image to TinyGo v0.25.0

- subo/command/compute_create_token.go
> docs: add context before printing token

- root.go
- subo/command/dev.go
Closes #361. I just removed the mentions to Atmo rather than replacing them, but could do the opposite if that would be preferred ofc!
> fix: remove user-facing Atmo mentions

- root.go
> feat!: Remove entrypoint to dev subcommand

- subo/release/check.go
io/ioutil has been deprecated since 1.16
> chore: Cleanup lint for deprecated package
