suborbital/subo

templates/project/helloworld/src/lib.rs
The helloworld project https://atmo.suborbital.dev/getstarted failed to build with:
```
Updating crates.io index
Downloading crates ...
Downloaded suborbital v0.6.3
Compiling suborbital v0.6.3
Compiling helloworld v0.1.0 (/root/runnable)
error[E0433]: failed to resolve: use of undeclared crate or module `util`
--> src/lib.rs:8:27
|
8 |         let body_string = util::to_string(body);
|                           ^^^^ use of undeclared crate or module `util`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
error: could not compile `helloworld`
```
=> Add missing util import

subo/command/build.go, subo/util/templates.go
The `subo dev` command was failing because projects created with subo had 700 permissions, which didn't agree with Docker on Debian/Ubuntu. This is resolved by changing to 777.
Resolves #40 
The `subo build` command was refraining from returning an error when not bundling (not sure why I made that decision...) and that was causing subo-in-docker to return 0, causing subo-out-of-docker to think the command had succeeded, thus continuing to bundle based on stale builds.
Resolves #42
=> Fix issues with build and create project commands

Makefile, subo/command/create_release.go, subo/features/development.go, subo/features/public.go, subo/root.go, subo/util/version_check.go
This adds the `subo create release` command:
`subo create release v0.1.0 Beta-1 --prerelease` 
It uses git, the gh CLI, and configurable make commands to run release workflows.
Currently only available when compiling with the `development` flag, use `make subo/dev`
=> Add 'create release' internal development command

templates/assemblyscript/package.json.tmpl, templates/assemblyscript/src/index.ts
This PR adds the custom abort handler and associated `asc` flag to the AssemblyScript template.
=> AS custom abort handler and asc flag

subo/context/directive.go
io/fs is not supported by Go 1.15, and so Gobinaries doesn't support it either.
=> Remove need for io/fs

templates/rust/src/lib.rs.tmpl, templates/swift/Sources/{{ .Name }}.tmpl/main.swift.tmpl
Closes #95. 
Initialization code for wasm runnables is now expected to appear in a module's `_start` function instead of `init`, so this PR updates the templates to produce source code this way.
=> Update wasm runnable templates

Dockerfile, builder/builder.mk, builder/context/buildcontext.go, builder/context/native.go, builder/context/prereq.go, builder/docker/tinygo/Dockerfile, subo/command/create_runnable.go
This PR adds TinyGo support to the Subo command line tool.
Because this was developed on an M1 Mac and tinygo doesn't provide public arm64 images, the TinyGo builder image has to build TinyGo from source. 
Notes:
- on M1 the tinygo compiler needs to be built from source, so this image is quite thicc (it could be smaller on other platforms)
- if Reactr is updated, run `docker build` with the `--no-cache` flag
- for now, this Dockerfile depends on a Reactr branch for the tinygo library
To run:
```
docker build . -f builder/docker/tinygo/Dockerfile -t suborbital/builder-tinygo:v0.1.0
subo create runnable hello-foobar --lang tinygo --repo jagger27/runnable-templates --branch jagger/add-tinygo-template --update-templates
```
The built module can then be run easily in Sat.
**Depends on**: …
=> Add TinyGo support to Subo

.github/workflows/release.yml, .goreleaser.yml
Adds an action that will update releases (when tags are created) uploading binaries and annotating the release notes with a `git diff`. If you don't want the diff, we can set the fetch depth back to 1 and just upload binaries.
Currently configured to build amd64/arm64 for Linux and macOS.
Closes #106
=> Add goreleaser

Dockerfile, builder/builder.go, builder/context/buildcontext.go, builder/context/native.go
This adds a "workaround" to support JSON in Assemblyscript by adding a compiler flag "analyzer" that automatically checks to see if the `--transform` flag is needed to build an AS module.
It's a bit hacky, but is the least bad way I could think to do it.
=> Add compiler flags

builder/docker/tinygo/Dockerfile
- explicitly clones tagged version of TinyGo to avoid future breakages
- uses Binaryen optimizer stage!
Fixes #127 
Thanks @k33g for the report!
=> Fix tinygo builder Dockerfile

templates/scc-k8s/.suborbital/scc-controlplane-deployment.yaml.tmpl
This change tells the builder where to find the control plane so that Sat can connect and download its config
=> Add builder control_plane env value

subo/command/create_runnable.go
PR for #119 
Based on the conv in #119,  we want to delete the output dir of `sudo create runnable` for any failure that occurs in `CreateRunnableCmd`.
Replication steps:
```console
subo create runnable foobar --lang somethingnotsupported
```
`CreateRunnableError`s `Error` will also act as a cleanup function for these failures. atm, it's only deleting the output dir.
Ideally, cobra.Command would have a error callback feature when RunE fails... maybe we'll get one for Xmas. https://github.com/spf13/cobra/issues/914
Off topic, I wish cobra.Command had a error callback for each of their run `E` functions (`RunE`, `PreRunE`, `PostRunE`, `PersistentPreRunE`, `PersistentPostRunE`). They have a callback for when[ flag parsing fails](https://pkg.go.dev/github.com/spf13/cobra#Command.SetFlagErrorFu …
=> New Error and cleanup function for CreateRunnableCmd failures

builder/template/templates.go, main.go, subo/command/compute_deploy_core.go, subo/command/flags.go, subo/localproxy/proxy.go
This adds this to `subo compute deploy core`:
--reset: resets the `docker-compose.yaml` or K8s manifests to the default template (does not update templates)
The reset behaviour is disabled unless the flag is passed, which is a breaking change.
If there are no manifests in the current directory, it will create them. If no templates exist, the latest are downloaded.
Resolves https://github.com/suborbital/subo/issues/152
=> Add --reset flag to compute deploy core command

subo/release/check.go
PR for #168
The bug is caused when an empty string is saved as the cached timestamp for `version check`.
ℹ️ failed to getLatestVersion: failed to getTimestampCache: failed to getTimestampCache: failed to parse cached timestamp: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
Until this patch, subo did not purge the bad cache for `version check` and so `version check` will continuously fail. Note, `version check` ran in a separate thread so it didn't affect any executed command.
We also applied the same patch for `version check`'s cached repo release data as well. Not because we saw the same error for it, but it "could" happen in the future if a bad repo release data was cached some how.
Cheers! 🍻
=>  bug patch: purge bad data cache from version check

Makefile, root.go, subo/release/info.go, subo/release/release.mk
If for some reason Subo is built without the Makefile it falls back to the old output style. Timestamps are RFC3339 UTC format.
Example:
```
subo -v
Subo CLI v0.2.1 ad5be137b5b8dd68e2897459f5efa45d4534451c (Built at 2021-11-24T19:36:17Z)
```
=> Add commit hash and build time to --version output

builder/context/directive.go, builder/template/config.go, builder/template/templates.go, subo/command/create_runnable.go, subo/release/check.go, subo/util/cache.go, subo/util/mkdir.go, subo/util/permissions.go, subo/util/token.go
I went through Subo and adjusted the file permissions according to the following rules:
- directories are all `0755`
- locally cached and temporary files are `0644`
- runnable source files are `0600`
Fixes #171
=> Reduce file and folder permissions across subo

.github/workflows/dispatch-on-release.yml
Closes #182 
Adds workflow on release for subo to send data to the homebrew-subo repository to update the homebrew formula.
The three pieces of data to be sent are tag, sha256 of the release, and the url of the newly created release.
These are used in the formula. See https://github.com/suborbital/homebrew-subo/pull/4
The only niggle is that the job needs a personal access token with the public_repo scope. See https://github.com/peter-evans/repository-dispatch#token
That needs to be saved as REPOTOKEN.
=> [Issue-182] Adds a workflow to dispatch data on release

docs/test/example.md, docs/test/greeting_test.go, docs/test/greetings.go, root.go, subo/command/docs.go, subo/release/check.go
PR for #22 
Create a set of commands to:
1. `subo docs build [dir] [--output]` recursively generate documentation with appropriate code snippets inserted at the directory `--output` (optional, otherwise [dir] is used as the output dir as well)
2. `subo docs test [dir]` recursively test the code snippets without documentation generation (although we do generate documentation to test the templates, but it's at subo's cache directory)
<details>
<summary> Details </summary>
This is done by using template actions and [testable examples](https://go.dev/blog/examples).
docs api uses the actions format ``, where package is the go package name and `example name` can be a package ("{go package}:[example name]") or a function example.
Note, only packages and functions with testable examples can be …
=> feat(cli): initial version of `subo doc` to build and test docs snippets

Makefile, builder/builder.go, builder/context/prereq.go, builder/context/prereq_test.go, go.mod
Closes #123 
Adds templating to prerequisite commands
* moves the logic to do that onto the `Prereq` struct and out of the builder
* adds tests
* adds make target for easier local vendoring (not related to functionality)
* reorders imports
=> feat(builder): Introduce templating for prereq commands

builder/docker/javascript/Dockerfile
Closes #214 
Although we're the root user, node runs npm scripts as the owner of the current directory (see https://github.com/npm/cli/issues/4095#issuecomment-996261636). This change allows anyone to access our home directory (which is more or less empty), so no matter what user owns the mounted runnable directory, `npm` will be able to write to caches/etc.
I also noticed an issue with Javy not being able to write to `/root/cargo`, and this solves that too.
This also avoids having to change any file permissions on the host system.
=> fix(builder): Fix JS builder permissions on linux

.github/workflows/ci.yml, Dockerfile
Currently make `subo/docker` fails because it doesn't have access to the complete source. 
This adds the missing packages to the docker file copy directive
=> bug: Add missing packages to subo dockerfile

builder/native.go
without cargo vendor
```
Finished release [optimized] target(s) in 24.34s
✅ DONE: rusty was built -> /root/runnable/rusty.wasm
real    0m26.111s
user    0m0.090s
sys     0m0.051s
```
with cargo vendor
```
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
Finished release [optimized] target(s) in 0.01s
✅ DONE: rusty was built -> /root/runnable/rusty.wasm
real    0m7.056s
user    0m0.065s
sys     0m0.061s
```
=> feat(builder): Vendor rust dependencies for faster builds

subo/command/compute_deploy_core.go, subo/util/permissions.go
Adds `PermExecutable` and `PermExecutablePrivate` for when Subo
is downloading executable files.
=> chore(util): add executable permissions

Dockerfile, Makefile, main.go, subo/release/check.go, update_checker.go, update_checker_docker.go
This is done by introducing a go build flag.
(Merge after #239)
Closes #242
=> fix: Remove update checking when inside Docker

Makefile, builder/builder.mk
Buildkit is enabled by default when `buildx` is invokved, but `build` is not. In the future, we will probably use some of the buildkit features.
=> chore(docker): enable buildkit for non-buildx calls

builder/builder.go, builder/template/templates.go, deployer/k8sdeployer.go, packager/dockerimagepackager.go, publisher/dockerpublisher.go, subo/command/build.go, subo/command/compute_deploy_core.go, subo/command/create_project.go, subo/command/create_release.go, subo/command/dev.go, subo/util/exec.go, subo/util/exec_test.go
This PR includes one small breaking change to the builder's `ForDirectory`—it now accepts an `io.Writer` as the second argument that will have build output written to it. It can be `nil`.
=> feat!: Make build output streamable

.github/workflows/ci.yml, Makefile, builder/docker/tinygo/Dockerfile
Break up the smoketest into N number of tests, one per language.
Also builds the dev `builder` images locally instead of pulling.
=> chore(ci): make the smoketest a matrix

.github/workflows/ci.yml
Adds a GitHub script (which is just Javascript with the GAPI authenticated) that collects the repository (fork) and branch of the commit that triggered the event.
This is to allow `subo` to checkout forks in CI.
`branch` is either a branch name or tag name.
/cc @yashikajotwani12
=> chore(ci): parse repo and branch from github context

.github/workflows/ci.yml
Builds a suborbital/subo:dev image once and uploads the artifact as a tarball, which the smoke tests will download and use instead of pulling from Docker Hub.
=> chore: build subo:dev image for builder smoke tests

Dockerfile
Uses multistage build to simplify the Dockerfile. Places the binary in `/go/bin/subo` as thats where the builder images expect it to be.
=> chore: simplify Dockerfile

.github/workflows/tinygo-base.yml
The inputs field is populated so push is properly set to `false`.
=> chore(ci): use one build job for tinygo-base

.github/workflows/ci.yml
Tags a `localhost:5000/suborbital/subo:dev` image that is pushed to a local Docker registry (one per job) that is consumed by the builder job.
This is to allow `docker buildx` to use the locally built `suborbital/subo:dev` instead of pulling from Docker.io. `docker buildx` does not allow you to use locally built and cached images from the Docker daemon -- they must be provided via an HTTP registry.
=> chore: fix subo:dev build image for other builders

builder/docker/tinygo/Dockerfile
Forgotten before, this updates the image that tinygo will run on with 1.18.
=> feat: update tinygo image to go 1.18

builder/docker/javascript/Dockerfile
Uses a pre-built and versioned javy, rather than building it from source everytime.
=> chore: Use javy image

.github/workflows/ci.yml
Subo requires a branch to be passed to it during the test workflow. A
tag is not a branch. This change ensures that tag references (ie:
`refs/tags/v1.0.0` retain the tags/ prefix required by subo.
=> chore: fix tag based release checkouts

.github/workflows/ci.yml
Subo requires Docker images to build runnables. This change ensures that
all images are built and pushed before building and pushing the binary.
=> chore: release binary after docker images

subo/repl/repl.go
Currently, there's only one option but that option reads as though it is two separate options. This clarifies that both create and edit are done via this single option.
=> chore: Clarify first REPL option

subo/command/compute_deploy_core.go
Compose v2 is the future, but it may not be present on all installs.
This PR prefers `docker compose` but falls back to `docker-compose` if Compose v2 is not detected.
Alternative to #353
Fixes #344
=> fix: Prefer `docker compose` to `docker-compose`

project/context.go, subo/command/create_project.go, subo/command/dev.go, subo/release/version.go
Even after @cohix's fixes `subo` was completely broken with `create project` failing with a Template parsing error. Turns out it tried to deserialize `.AtmoVersion` in the helloworld project template and threw a fit when it couldn't find the data. This parameter got renamed to `.DeltavVersion` earlier, but I actually ended up changit it here to `.RuntimeVersion`, so that we rely less on branding across serialization boundaries to avoid issues like this in the future.
Still, that wasn't all, DeltaV ditches `headless` mode completely (as it is "by default headless"), so the setting got factored out in `subo` which was also breaking templates.
Note that this PR relies on these two updates on the `runnable-templates` `vmain` branch: [version](https://github.com/suborbital/runnable-templates/co …
=> refactor: runnable-templates, fix create project

.github/renovate.json5, builder/docker/tinygo/Dockerfile
Uses a Regex string and manager to capture the version and update it.
Example of the regex at: https://regex101.com/r/lfZC3R/1
=> chore: Use renovate to update tiny-go

.github/workflows/ci.yml
Uses the Go version describe in the Go modules file instead of whatever is in the workflow.
Also uses the built in cache to `setup-go` over the `actions-cache` action (essentially a no-op).
=> chore: Use Go version from gomods

subo/command/se2_deploy.go, subo/release/version.go
Moves over to SE2 template names. Updates SE2 to `v0.4.1`.
=> chore: Update subo to use SE2 images over SCC/SCN

project/context.go, subo/command/create_module.go, subo/command/create_project.go, subo/command/se2_deploy.go, subo/release/check.go, subo/release/info.go, subo/release/version.go
E2Core version is currently hardcoded into the templates (suborbital/templates) repository directly. This commit templates the release.RuntimeVersion (which represents E2Core) into the templates, rather than rely on the hardcoded tag in the template itself.
This commit also makes some small changes that:
- Rename FFIVersion to SDKVersion (as Reactr will be SDK)
- Set release vars as consts
- Differentiates versions and tags
=> fix: deploy the e2core version from subo, not the templates

subo/command/se2_deploy.go
Currently there is no way that you can update the remote deploy templates from the `se2 deploy` command. This PR adds the `--update-templates` flag that will update the templates before manifest generation.
=> feat: Add update templates flag to se2 deploy

Dockerfile, builder/docker/tinygo/Dockerfile, go.mod
Updates Go and TinyGo builder image to Go 1.19
=> chore: Update Go to 1.19
